name: 'stravadw'
version: '1.0.0'
config-version: 2

profile: 'stravadw'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stravadw:
    gold:
      +schema: gold
      +materialized: table

seeds:
  stravadw:
    +schema: gold
